### ISSUE TITLE
期待新的图标感谢

### ISSUE THREAD

**Issue by qhy5697062** [Aoyt520/jiumeiquanX#1]
苹果屏蔽更新的图标还有国旗们😄

**Comment by Aoyt520** [comment]
谢谢支持，我明天处理下国旗。你的屏蔽更新图标我今晚回去找下





------------------ 原始邮件 ------------------
发件人: qhy5697062 <notifications@github.com&gt;
发送时间: 2020年3月18日 20:04
收件人: Aoyt520/jiumeiquanX <jiumeiquanX@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Aoyt520/jiumeiquanX] 期待新的图标感谢 (#1)

**Comment by qhy5697062** [comment]
谢谢
